### ISSUE TITLE
fix logic

### ISSUE THREAD

**Issue by c4nzin** [sumdmt/Calculator#1]
calculator.js 

```javascript
let screen = document.querySelector(".inner");
let buttons = document.querySelectorAll(".btn");
let clear = document.querySelector(".clear");
let equal = document.querySelector(".equal");

screen.value = "0";

grabAllButtons();

equal.addEventListener("click", showResult);

clear.addEventListener("click", clearScreen);

function clearScreen() {
  // prettier-ignore
  return screen.value = "0";
}

function showResult() {
  if (screen.value == "") {
  } else {
    let answer = eval(screen.value);

    screen.value = answer;
  }
}

function grabAllButtons() {
  buttons.forEach(function (button) {
    button.addEventListener("click", function (e) {
      let value = e.target.dataset.num;
      screen.value += value;
    });
  });
}

```

index.html

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="calculator.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Calculator</title>
  </head>
  <body>
    <section>
      <input type="text" class="inner" />
      <div class="first">
        <button type="button" class="zero btn" data-num="0">0</button>
        <button type="button" class="one btn" data-num="1">1</button>
        <button type="button" class="two btn" data-num="2">2</button>
        <button type="button" class="three btn" data-num="3">3</button>
        <button type="button" class="four btn" data-num="4">4</button>
        <button type="button" class="five btn" data-num="5">5</button>
        <button type="button" class="six btn" data-num="6">6</button>
        <button type="button" class="seven btn" data-num="7">7</button>
        <button type="button" class="eight btn" data-num="8">8</button>
        <button type="button" class="nine btn" data-num="9">9</button>
        <button type="button" class="zero2 btn" data-num="00">00</button>
        <button type="button" class="plus btn" data-num="+">+</button>
        <button type="button" class="minus btn" data-num="-">-</button>
        <button type="button" class="div btn" data-num="/">/</button>
        <button type="button" class="mul btn" data-num="*">*</button>
        <button type="button" class="dot btn" data-num=".">.</button>
        <button type="button" class="clear">C</button>
        <button type="button" class="equal">=</button>
      </div>
    </section>
    <script defer src="calculator.js"></script>
  </body>
</html>

```

calculator.css

```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body {
  display: flex;
  justify-content: center;
  align-items: center;
  background: white;
  min-height: 100vh;
}
section {
  position: relative;
  width: 390px;
  height: 600px;
  background-color: black;
  border-radius: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.inner {
  position: relative;
  border-radius: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 360px;
  height: 80px;
  font-size: 2em;
  text-align: right;
  background: orange;
  bottom: 200px;
  border: none;
  outline: none;
  float: left;
  left: 15px;
  padding-right: 8px;
  color: white;
}
.first {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 360px;
  height: 360px;
  background: black;
  top: 40px;
  border-radius: 20px;
}
button {
  position: absolute;
  width: 60px;
  height: 60px;
  font-size: 2em;
  border-radius: 20px;
  border: none;
  outline: none;
}
.equal {
  bottom: 10px;
  right: 200px;
  top: 360px;
  width: 160px;
  background: orange;
  color: white;
}
.clear {
  top: 360px;
  right: 30px;
  background: orange;
  color: white;
  width: 160px;
}

.one {
  top: 10px;
  right: 300px;
}
.two {
  top: 10px;
  right: 210px;
}
.three {
  top: 10px;
  right: 120px;
}
.plus {
  top: 100px;
  right: 30px;
  height: 60px;
  background: orange;
  color: white;
}
.four {
  top: 100px;
  right: 300px;
}
.five {
  top: 100px;
  right: 210px;
}
.six {
  top: 100px;
  right: 120px;
}
.minus {
  bottom: 290px;
  right: 30px;
  background: orange;
  color: white;
}
.dot {
  top: 280px;
  right: 120px;
  background: orange;
  color: white;
}
.seven {
  top: 190px;
  right: 300px;
}
.eight {
  top: 190px;
  right: 210px;
}
.nine {
  top: 190px;
  right: 120px;
}
.mul {
  top: 193px;
  right: 30px;
  background: orange;
  color: white;
}
.div {
  top: 280px;
  right: 30px;
  background: orange;
  color: white;
}
.zero {
  top: 280px;
  right: 300px;
}
.zero2 {
  top: 280px;
  right: 210px;
}
```
